/**
 * Demo seed data — Florentin, Tel Aviv.
 *
 * This is what the app runs on when no Supabase project is configured, so a
 * fresh clone is useful immediately. The shape matches exactly what the real
 * `search_tools_nearby` RPC returns, including the two privacy properties:
 *   - coordinates here are the FUZZED points, offset 100–200 m from a notional
 *     home address, which is not in this file at all;
 *   - distances are pre-rounded to 50 m.
 *
 * The same set is mirrored in `supabase/migrations/*_seed_dev.sql` so demo mode
 * and a local Supabase look the same.
 */

import type {
  BorrowRequest,
  Conversation,
  IncludedItem,
  Message,
  PickupWindow,
  PublicProfile,
  ToolDetail,
  Transaction,
} from '@/types/domain';

export const FLORENTIN = { latitude: 32.0553, longitude: 34.7688 };

/** Offset a point by metres — used to place seed tools believably around the centre. */
function offset(metresNorth: number, metresEast: number) {
  return {
    latitude: FLORENTIN.latitude + metresNorth / 111_320,
    longitude:
      FLORENTIN.longitude + metresEast / (111_320 * Math.cos((FLORENTIN.latitude * Math.PI) / 180)),
  };
}

/**
 * The same pickup windows on every day of the week.
 *
 * Real listings vary by day; a demo that only opens on Tuesdays shows an empty
 * "Available today" panel six days out of seven, which reads as a bug.
 */
function everyDay(slots: [string, string][]): PickupWindow[] {
  return [0, 1, 2, 3, 4, 5, 6].flatMap((weekday) =>
    slots.map(([startTime, endTime]) => ({ weekday, startTime, endTime })),
  );
}

const EVENINGS = everyDay([
  ['18:00', '20:00'],
  ['20:00', '22:00'],
]);
const DAYTIME = everyDay([
  ['09:00', '12:00'],
  ['17:00', '20:00'],
]);
const AFTER_WORK = everyDay([['17:30', '21:00']]);

const item = (label: string, icon: IncludedItem['icon'] = 'item'): IncludedItem => ({ label, icon });

export const demoProfiles: Record<string, PublicProfile> = {
  daniel: {
    id: 'p-daniel',
    firstName: 'Daniel',
    avatarUrl: null,
    neighbourhood: 'Dizengoff Center',
    rating: 4.9,
    ratingCount: 12,
    completedExchanges: 12,
    verificationLevel: 'phone',
    memberSince: '2026-01-18T09:00:00.000Z',
  },
  yossi: {
    id: 'p-yossi',
    firstName: 'Yossi',
    avatarUrl: null,
    neighbourhood: 'Florentin',
    rating: 4.9,
    ratingCount: 23,
    completedExchanges: 31,
    verificationLevel: 'phone',
    memberSince: '2026-03-04T09:00:00.000Z',
  },
  adi: {
    id: 'p-adi',
    firstName: 'Adi',
    avatarUrl: null,
    neighbourhood: 'Florentin',
    rating: 4.8,
    ratingCount: 19,
    completedExchanges: 23,
    verificationLevel: 'email',
    memberSince: '2026-05-19T09:00:00.000Z',
  },
  michal: {
    id: 'p-michal',
    firstName: 'Michal',
    avatarUrl: null,
    neighbourhood: 'Neve Tzedek',
    rating: 4.7,
    ratingCount: 9,
    completedExchanges: 11,
    verificationLevel: 'phone',
    memberSince: '2026-06-28T09:00:00.000Z',
  },
  omer: {
    id: 'p-omer',
    firstName: 'Omer',
    avatarUrl: null,
    neighbourhood: 'Florentin',
    rating: 4.6,
    ratingCount: 7,
    completedExchanges: 9,
    verificationLevel: 'email',
    memberSince: '2026-04-11T09:00:00.000Z',
  },
  noa: {
    id: 'p-noa',
    firstName: 'Noa',
    avatarUrl: null,
    neighbourhood: 'Shapira',
    rating: 4.9,
    ratingCount: 15,
    completedExchanges: 18,
    verificationLevel: 'phone',
    memberSince: '2026-02-02T09:00:00.000Z',
  },
  dana: {
    id: 'p-dana',
    firstName: 'Dana',
    avatarUrl: null,
    neighbourhood: 'Florentin',
    rating: 4.9,
    ratingCount: 6,
    completedExchanges: 6,
    verificationLevel: 'email',
    memberSince: '2026-07-15T09:00:00.000Z',
  },
};

/**
 * A seed row. `includedItems` and `pickupWindows` are optional here and filled
 * in below — most listings in a real neighbourhood have neither, and a demo
 * where every single tool ships with a case and a charger looks fabricated.
 */
type SeedTool = Omit<ToolDetail, 'owner' | 'ownerProfile' | 'includedItems' | 'pickupWindows'> & {
  ownerKey: keyof typeof demoProfiles;
  includedItems?: IncludedItem[];
  pickupWindows?: PickupWindow[];
};

const seed: SeedTool[] = [
  {
    id: 't-drill',
    title: 'Bosch Cordless Drill',
    toolType: 'cordless-drill',
    brand: 'Bosch',
    model: 'GSB 18V-55',
    isModelConfirmed: true,
    categoryId: 1,
    categorySlug: 'power-tools',
    paymentMode: 'free',
    pricePerDayAgorot: null,
    currency: 'ILS',
    availabilityMode: 'now',
    risk: 'medium',
    neighbourhood: 'Dizengoff Center',
    distanceM: 300,
    coords: offset(180, 220),
    photoUrl: null,
    photos: [],
    description:
      '18V cordless drill suitable for wood, metal and light masonry. Includes battery and charger.',
    condition: 'good',
    accessories: 'One battery, charger, carry case',
    includedItems: [item('18V Battery', 'battery'), item('Charger', 'charger'), item('Case', 'case')],
    pickupWindows: EVENINGS,
    instructions: 'The clutch ring is stiff — turn it firmly.',
    maxBorrowDays: 3,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 11,
    createdAt: '2026-08-02T10:00:00.000Z',
    ownerKey: 'daniel',
  },
  {
    id: 't-jigsaw',
    title: 'Makita Jigsaw',
    toolType: 'jigsaw',
    brand: 'Makita',
    model: null,
    isModelConfirmed: false,
    categoryId: 8,
    categorySlug: 'woodworking',
    paymentMode: 'offline',
    pricePerDayAgorot: 1500,
    currency: 'ILS',
    availabilityMode: 'dates',
    risk: 'high',
    neighbourhood: 'Florentin',
    distanceM: 550,
    coords: offset(-320, 450),
    photoUrl: null,
    photos: [],
    description: 'Corded jigsaw for curves in wood and thin metal. Comes with three blades.',
    condition: 'good',
    accessories: 'Three blades, 4 m cable',
    includedItems: [item('3 blades'), item('Case', 'case')],
    pickupWindows: AFTER_WORK,
    instructions: null,
    maxBorrowDays: 2,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 4,
    createdAt: '2026-08-09T10:00:00.000Z',
    ownerKey: 'adi',
  },
  {
    id: 't-ladder',
    title: '3 m Ladder',
    toolType: 'ladder',
    brand: null,
    model: null,
    isModelConfirmed: false,
    categoryId: 5,
    categorySlug: 'ladders',
    paymentMode: 'free',
    pricePerDayAgorot: null,
    currency: 'ILS',
    availabilityMode: 'ask',
    risk: 'medium',
    neighbourhood: 'Neve Tzedek',
    distanceM: 700,
    coords: offset(560, -420),
    photoUrl: null,
    photos: [],
    description: 'Three-metre folding ladder. Light enough to carry, heavy enough to feel safe.',
    condition: 'good',
    accessories: null,
    includedItems: [],
    pickupWindows: DAYTIME,
    instructions: 'It lives on the balcony — message me and I will bring it down.',
    maxBorrowDays: 2,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 7,
    createdAt: '2026-07-21T10:00:00.000Z',
    ownerKey: 'michal',
  },
  {
    id: 't-washer',
    title: 'Kärcher Pressure Washer',
    toolType: 'pressure-washer',
    brand: 'Kärcher',
    model: 'K5',
    isModelConfirmed: false,
    categoryId: 4,
    categorySlug: 'cleaning',
    paymentMode: 'offline',
    pricePerDayAgorot: 2500,
    currency: 'ILS',
    availabilityMode: 'dates',
    risk: 'medium',
    neighbourhood: 'Shapira',
    distanceM: 1200,
    coords: offset(-1050, 600),
    photoUrl: null,
    photos: [],
    description: 'Pressure washer for balconies, tiles and bikes. Hose and two nozzles included.',
    condition: 'like_new',
    accessories: 'Hose, two nozzles, detergent bottle',
    includedItems: [item('Hose'), item('2 nozzles'), item('Detergent')],
    pickupWindows: DAYTIME,
    instructions: 'Needs a tap connection — bring an adapter if yours is unusual.',
    maxBorrowDays: 2,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 0,
    createdAt: '2026-08-14T10:00:00.000Z',
    ownerKey: 'noa',
  },
  {
    id: 't-drillset',
    title: 'Black+Decker Drill Set',
    toolType: 'drill-set',
    brand: 'Black+Decker',
    model: null,
    isModelConfirmed: false,
    categoryId: 1,
    categorySlug: 'power-tools',
    paymentMode: 'free',
    pricePerDayAgorot: null,
    currency: 'ILS',
    availabilityMode: 'now',
    risk: 'medium',
    neighbourhood: 'Shapira',
    distanceM: 1100,
    coords: offset(-980, -420),
    photoUrl: null,
    photos: [],
    description: 'Drill plus a full bit set in a hard case. Good for flat-pack and picture hooks.',
    condition: 'worn',
    accessories: null,
    includedItems: [item('Battery', 'battery'), item('Charger', 'charger'), item('Bit set', 'case')],
    pickupWindows: EVENINGS,
    instructions: 'Bring your own masonry bits if you are drilling brick.',
    maxBorrowDays: 4,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 19,
    createdAt: '2026-08-01T10:00:00.000Z',
    ownerKey: 'omer',
  },
  {
    id: 't-hammerdrill',
    title: 'Makita Rotary Hammer',
    toolType: 'rotary-hammer',
    brand: 'Makita',
    model: null,
    isModelConfirmed: false,
    categoryId: 1,
    categorySlug: 'power-tools',
    paymentMode: 'offline',
    pricePerDayAgorot: 1800,
    currency: 'ILS',
    availabilityMode: 'ask',
    risk: 'high',
    neighbourhood: 'Florentin',
    distanceM: 650,
    coords: offset(520, 390),
    photoUrl: null,
    photos: [],
    description: 'SDS rotary hammer for concrete. Three masonry bits included.',
    condition: 'good',
    accessories: '6, 8 and 10 mm masonry bits',
    includedItems: [item('3 SDS bits'), item('Case', 'case'), item('Side handle')],
    pickupWindows: AFTER_WORK,
    instructions: 'Wear eye protection. Check for cables before you drill.',
    maxBorrowDays: 1,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 2,
    createdAt: '2026-08-20T10:00:00.000Z',
    ownerKey: 'adi',
  },
  {
    id: 't-hedge',
    title: 'Hedge Trimmer',
    toolType: 'hedge-trimmer',
    brand: 'Ryobi',
    model: null,
    isModelConfirmed: false,
    categoryId: 3,
    categorySlug: 'gardening',
    paymentMode: 'free',
    pricePerDayAgorot: null,
    currency: 'ILS',
    availabilityMode: 'now',
    risk: 'high',
    neighbourhood: 'Florentin',
    distanceM: 1950,
    coords: offset(-1750, -900),
    photoUrl: null,
    photos: [],
    description: 'Electric hedge trimmer, 45 cm blade. Good for a balcony hedge or small garden.',
    condition: 'good',
    accessories: 'Blade guard',
    instructions: null,
    maxBorrowDays: 2,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 5,
    createdAt: '2026-08-06T10:00:00.000Z',
    ownerKey: 'adi',
  },
  {
    id: 't-toolkit',
    title: 'Screwdriver & Spanner Set',
    toolType: 'hand-tool-set',
    brand: null,
    model: null,
    isModelConfirmed: false,
    categoryId: 2,
    categorySlug: 'hand-tools',
    paymentMode: 'free',
    pricePerDayAgorot: null,
    currency: 'ILS',
    availabilityMode: 'now',
    risk: 'low',
    neighbourhood: 'Florentin',
    distanceM: 1550,
    coords: offset(1450, -520),
    photoUrl: null,
    photos: [],
    description: 'A full set of screwdrivers and spanners in a case. Enough for most flat-pack jobs.',
    condition: 'good',
    accessories: 'Case',
    instructions: null,
    maxBorrowDays: 7,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 0,
    createdAt: '2026-07-30T10:00:00.000Z',
    ownerKey: 'dana',
  },
  {
    id: 't-tilecutter',
    title: 'Manual Tile Cutter',
    toolType: 'tile-cutter',
    brand: 'Rubi',
    model: null,
    isModelConfirmed: false,
    categoryId: 9,
    categorySlug: 'home-repair',
    paymentMode: 'offline',
    pricePerDayAgorot: 2000,
    currency: 'ILS',
    availabilityMode: 'dates',
    risk: 'medium',
    neighbourhood: 'Shapira',
    distanceM: 1650,
    coords: offset(-1500, 700),
    photoUrl: null,
    photos: [],
    description: 'Manual tile cutter up to 60 cm. Clean cuts on ceramic, harder work on porcelain.',
    condition: 'good',
    accessories: null,
    instructions: null,
    maxBorrowDays: 3,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 8,
    createdAt: '2026-08-11T10:00:00.000Z',
    ownerKey: 'noa',
  },
  {
    id: 't-paint',
    title: 'Paint Roller Kit & Tray',
    toolType: 'paint-roller',
    brand: null,
    model: null,
    isModelConfirmed: false,
    categoryId: 6,
    categorySlug: 'painting',
    paymentMode: 'free',
    pricePerDayAgorot: null,
    currency: 'ILS',
    availabilityMode: 'now',
    risk: 'low',
    neighbourhood: 'Florentin',
    distanceM: 2350,
    coords: offset(2000, -1200),
    photoUrl: null,
    photos: [],
    description: 'Two rollers, an extension pole and a tray. Washed and ready.',
    condition: 'good',
    accessories: 'Extension pole, tray, two sleeves',
    instructions: 'Please rinse the sleeves before returning.',
    maxBorrowDays: 5,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 1,
    createdAt: '2026-08-18T10:00:00.000Z',
    ownerKey: 'michal',
  },
  {
    id: 't-trolley',
    title: 'Folding Hand Trolley',
    toolType: 'hand-trolley',
    brand: null,
    model: null,
    isModelConfirmed: false,
    categoryId: 10,
    categorySlug: 'moving',
    paymentMode: 'free',
    pricePerDayAgorot: null,
    currency: 'ILS',
    availabilityMode: 'ask',
    risk: 'low',
    neighbourhood: 'Florentin',
    distanceM: 1850,
    coords: offset(-1700, 750),
    photoUrl: null,
    photos: [],
    description: 'Folding trolley, takes about 70 kg. Saved me three trips up four floors.',
    condition: 'worn',
    accessories: null,
    instructions: null,
    maxBorrowDays: 3,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 14,
    createdAt: '2026-07-25T10:00:00.000Z',
    ownerKey: 'omer',
  },
  {
    id: 't-tent',
    title: '4-Person Tent',
    toolType: 'tent',
    brand: 'Coleman',
    model: null,
    isModelConfirmed: false,
    categoryId: 11,
    categorySlug: 'camping',
    paymentMode: 'offline',
    pricePerDayAgorot: 4000,
    currency: 'ILS',
    availabilityMode: 'dates',
    risk: 'low',
    neighbourhood: 'Neve Tzedek',
    distanceM: 2100,
    coords: offset(1900, -900),
    photoUrl: null,
    photos: [],
    description: 'Four-person tent, dry and complete. Pegs and poles all present.',
    condition: 'good',
    accessories: 'Pegs, poles, groundsheet',
    instructions: 'Please return it dry or it will smell by next weekend.',
    maxBorrowDays: 7,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 3,
    createdAt: '2026-08-22T10:00:00.000Z',
    ownerKey: 'michal',
  },
  {
    id: 't-mower',
    title: 'Electric Lawn Mower',
    toolType: 'lawn-mower',
    brand: 'Bosch',
    model: null,
    isModelConfirmed: false,
    categoryId: 3,
    categorySlug: 'gardening',
    paymentMode: 'offline',
    pricePerDayAgorot: 3500,
    currency: 'ILS',
    availabilityMode: 'ask',
    risk: 'high',
    neighbourhood: 'Shapira',
    distanceM: 2600,
    coords: offset(-2400, 1100),
    photoUrl: null,
    photos: [],
    description: 'Corded mower for a small garden. Grass box included.',
    condition: 'good',
    accessories: 'Grass box, 10 m extension lead',
    instructions: 'Keep the cable behind you at all times.',
    maxBorrowDays: 2,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 6,
    createdAt: '2026-08-05T10:00:00.000Z',
    ownerKey: 'noa',
  },
  {
    id: 't-stud',
    title: 'Stud & Cable Detector',
    toolType: 'stud-detector',
    brand: 'Bosch',
    model: 'Truvo',
    isModelConfirmed: true,
    categoryId: 9,
    categorySlug: 'home-repair',
    paymentMode: 'free',
    pricePerDayAgorot: null,
    currency: 'ILS',
    availabilityMode: 'now',
    risk: 'low',
    neighbourhood: 'Florentin',
    distanceM: 1750,
    coords: offset(1600, 700),
    photoUrl: null,
    photos: [],
    description: 'Finds studs, metal and live wiring before you drill. Takes one 9V battery.',
    condition: 'like_new',
    accessories: null,
    instructions: null,
    maxBorrowDays: 5,
    depositAgorot: null,
    status: 'active',
    completedExchanges: 0,
    createdAt: '2026-08-24T10:00:00.000Z',
    ownerKey: 'yossi',
  },
];

export const demoTools: ToolDetail[] = seed.map((tool) => {
  const profile = demoProfiles[tool.ownerKey]!;
  const { ownerKey: _ownerKey, ...rest } = tool;
  return {
    ...rest,
    includedItems: tool.includedItems ?? [],
    // Anything without its own hours is an "ask me" listing that still needs a
    // sensible answer on the detail screen.
    pickupWindows: tool.pickupWindows ?? AFTER_WORK,
    owner: {
      id: profile.id,
      firstName: profile.firstName,
      avatarUrl: profile.avatarUrl,
      rating: profile.rating,
      ratingCount: profile.ratingCount,
    },
    ownerProfile: profile,
  };
});

/** The signed-in demo user. In demo mode "you" are Dana. */
export const DEMO_USER_ID = 'p-dana';

export const demoRequests: BorrowRequest[] = [
  {
    id: 'r-1',
    toolId: 't-toolkit',
    toolTitle: 'Screwdriver & Spanner Set',
    toolPhotoUrl: null,
    borrower: {
      id: 'p-omer',
      firstName: 'Omer',
      avatarUrl: null,
      rating: 4.6,
    },
    owner: { id: 'p-dana', firstName: 'Dana', avatarUrl: null, rating: 4.9 },
    status: 'pending',
    startAt: new Date(Date.now() + 86_400_000).toISOString(),
    endAt: new Date(Date.now() + 2 * 86_400_000).toISOString(),
    message: 'Assembling a wardrobe tomorrow evening — could I grab it around 18:00?',
    quotedTotalAgorot: null,
    paymentMode: 'free',
    createdAt: new Date(Date.now() - 3_600_000).toISOString(),
  },
];

/**
 * A due time, expressed as a wall-clock hour on a future day.
 *
 * The demo has to read "Return tomorrow by 21:00" whenever it is opened, so
 * the fixture is relative to now rather than a date that quietly becomes
 * last Tuesday.
 */
function atHour(daysFromNow: number, hour: number, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

/** Minutes ago, for a conversation that should look like it happened today. */
const minutesAgo = (n: number) => new Date(Date.now() - n * 60_000).toISOString();

export const demoTransactions: Transaction[] = [
  {
    id: 'x-1',
    requestId: 'r-0',
    toolId: 't-drill',
    toolTitle: 'Bosch Cordless Drill',
    toolPhotoUrl: null,
    ownerId: 'p-daniel',
    borrowerId: 'p-dana',
    counterparty: { id: 'p-daniel', firstName: 'Daniel', avatarUrl: null, rating: 4.9 },
    viewerRole: 'borrower',
    status: 'agreed',
    agreedTotalAgorot: null,
    currency: 'ILS',
    startAt: atHour(0, 18),
    dueAt: atHour(1, 21),
    pickedUpAt: null,
    returnedAt: null,
    ownerConfirmedReturn: false,
    completedAt: null,
    conversationId: 'c-1',
    hasRated: false,
  },
];

export const demoConversations: Conversation[] = [
  {
    id: 'c-1',
    toolId: 't-drill',
    toolTitle: 'Bosch Cordless Drill',
    toolPhotoUrl: null,
    transactionId: 'x-1',
    counterparty: { id: 'p-daniel', firstName: 'Daniel', avatarUrl: null },
    lastMessage: 'Pickup near Dizengoff Center.',
    lastMessageAt: minutesAgo(12),
    unread: true,
  },
];

export const demoMessages: Record<string, Message[]> = {
  'c-1': [
    {
      id: 'm-1',
      conversationId: 'c-1',
      senderId: 'p-dana',
      kind: 'text',
      body: 'Hi Daniel, can I borrow the drill today around 18:30?',
      createdAt: minutesAgo(24),
    },
    {
      id: 'm-2',
      conversationId: 'c-1',
      senderId: 'p-daniel',
      kind: 'text',
      body: "Yes — no problem. I'll be home after 18:00.",
      createdAt: minutesAgo(22),
    },
    {
      id: 'm-3',
      conversationId: 'c-1',
      senderId: 'p-dana',
      kind: 'text',
      body: 'Perfect, thanks!',
      createdAt: minutesAgo(21),
    },
    {
      id: 'm-4',
      conversationId: 'c-1',
      senderId: 'p-daniel',
      kind: 'text',
      body: 'Pickup near Dizengoff Center.',
      createdAt: minutesAgo(12),
    },
  ],
};

/** Exact pickup location, only ever revealed for an accepted transaction. */
export const demoPickupLocations: Record<string, { latitude: number; longitude: number; addressLine: string; pickupNotes: string | null }> = {
  'x-1': {
    ...offset(0, 0),
    addressLine: 'Dizengoff St 50, apartment 7, Tel Aviv',
    pickupNotes: 'Second floor, no lift. Ring the top bell.',
  },
};
